# Generated by Django 2.2.5 on 2019-09-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190910_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='formatted_address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
