# Generated by Django 2.2.5 on 2019-09-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_formatted_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lon',
            new_name='lng',
        ),
    ]
