# Generated by Django 2.2.5 on 2019-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190911_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Delhi', max_length=255),
            preserve_default=False,
        ),
    ]
